version: '3.8'

services:
  app:
    build:
      context: ./gol_y_cambio/backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=gol_y_cambio_v2
      - UPLOAD_FOLDER=/app/Almacenamiento 
    volumes:
      - C:/Users/merin/Escritorio/uni/TFG/Proyecto TFG V1/Almacenamiento:/app/Almacenamiento
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gol_y_cambio_v2
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
